name: mission-control
region: nyc
services:
  - name: mission-control
    github:
      repo: snkrpapi212/mission-control
      branch: dev
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_VERSION
        value: "20"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NEXT_PUBLIC_CONVEX_URL
        value: "https://tidy-salamander-925.eu-west-1.convex.cloud"
      - key: NEXT_PUBLIC_OPENCLAW_GATEWAY_URL
        value: "https://bilingually-flamier-alfonso.ngrok-free.dev"
      - key: OPENCLAW_GATEWAY_TOKEN
        value: "ray5fsgde3hxrb4y9hdkr9092f9reb51"
    health_check:
      http_path: /api/health
# Deploy: Fri Feb 27 21:03:14 UTC 2026
